In [1]:
import torch

lista = [[1,2,3],[4,5,6]]

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [2]:
import numpy as np

arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)

print(arr)
print(tns)

[[0.90259824 0.68012733 0.75533403 0.50465689]
 [0.65470561 0.93217437 0.59130892 0.51581489]
 [0.51910782 0.95631385 0.29047742 0.52688222]]
tensor([[0.9026, 0.6801, 0.7553, 0.5047],
        [0.6547, 0.9322, 0.5913, 0.5158],
        [0.5191, 0.9563, 0.2905, 0.5269]], dtype=torch.float64)


In [3]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3)

print(tns1)
print(tns0)
print(tnsr)


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[-0.4730, -1.8127, -0.9654],
        [-0.7572, -0.4120,  1.8370],
        [ 0.6501, -0.9541, -0.6672]])


In [4]:
arr = tnsr.data.numpy()
print(arr)

[[-0.47295028 -1.8127348  -0.9654396 ]
 [-0.7571788  -0.41197678  1.8370248 ]
 [ 0.650089   -0.9541218  -0.6671695 ]]


In [5]:

tns = torch.randn(10)

if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

print(device)

tns = tns.to(device)
print(tns)

cpu
tensor([-1.8023, -0.0393,  1.3534, -1.6568,  0.1834,  0.2129, -1.0455, -1.0999,
        -1.1914, -0.3651])


In [12]:
import torch
tns = torch.randn(9, 12)
print(tns.shape)
tns1 = tns[0:5, 0:4]
tns2 = tns[5:, 4:]

resultado = torch.mm(tns1, tns2)
print(resultado.size())

# print('TNS', tns)
# print('TNS1', tns1)
# print('TNS2', tns2)

torch.Size([9, 12])
torch.Size([5, 8])


In [16]:
import torch 
tns1 = torch.randn(7,7,3)
tns2 = torch.randn(147, 1)

print('TNS1', tns1)

tns1 = tns1.view(-1, 1)
soma = tns1 + tns2

print('TNS1', tns1)
print('TNS2', tns2)
print(soma)

TNS1 tensor([[[ 0.0808, -0.4111, -0.7374],
         [-1.1046, -1.1114,  0.2774],
         [ 0.5116,  0.6673,  1.7392],
         [-1.1743,  0.2097,  1.1715],
         [-0.1494,  0.9843,  1.2915],
         [ 1.5672,  0.7400, -0.7606],
         [ 0.9294, -0.9577, -0.1418]],

        [[-2.1511,  0.2239,  0.1253],
         [ 0.6223, -0.1800, -2.5662],
         [-1.5647,  0.1919, -1.5642],
         [ 0.6875, -1.5505, -0.3406],
         [-1.2886,  0.3799, -2.1388],
         [ 0.3232, -0.9394,  0.9103],
         [-1.9828,  1.7817, -0.8587]],

        [[-2.7074, -0.4676,  1.0042],
         [ 1.0826,  0.0123,  2.2048],
         [ 0.4810, -0.2024, -1.1803],
         [-0.7073,  0.9756,  0.4306],
         [-1.3679, -0.0251,  1.3076],
         [ 0.9010,  1.6478, -0.9009],
         [-0.0554,  1.5431,  0.0470]],

        [[-0.2967, -1.8485, -0.2543],
         [-0.2681, -1.2289,  0.8385],
         [-0.9358, -1.1840, -0.7288],
         [-0.6084, -1.2416, -1.0406],
         [-0.4797,  0.3405, -0.0992],
 